// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UORWeatherApp.Data;

#nullable disable

namespace UORWeatherApp.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    partial class WeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UORWeatherApp.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 1, 1),
                            Summary = "Mild",
                            TemperatureC = 15
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 1, 2),
                            Summary = "Warm",
                            TemperatureC = 22
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2024, 1, 3),
                            Summary = "Freezing",
                            TemperatureC = -5
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2024, 1, 4),
                            Summary = "Cool",
                            TemperatureC = 10
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2024, 1, 5),
                            Summary = "Hot",
                            TemperatureC = 28
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2024, 1, 6),
                            Summary = "Pleasant",
                            TemperatureC = 18
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2024, 1, 7),
                            Summary = "Chilly",
                            TemperatureC = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
